osx_image: xcode9.3
language: Swift
cache: cocoapods

before_install:
  - sudo gem install cocoapods
  - pod install --repo-update --project-directory=Example

script:
- set -o pipefail && xcodebuild clean build test -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' -workspace Example/SNPUtilities.xcworkspace -scheme SNPUtilities-Example | xcpretty 
